RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
STOCH_K_PERIOD = 14
STOCH_D_PERIOD = 3
STOCH_SMOOTH = 3
ADX_PERIOD = 14
EMA_SHORT = 50
EMA_LONG = 200
BOLLINGER_PERIOD = 20
BOLLINGER_STD = 2
VWAP_WINDOW = 20
CCI_PERIOD = 20
WILLIAMS_R_PERIOD = 14
OBV_EMA_PERIOD = 21
MFI_PERIOD = 14
AROON_PERIOD = 25
ROC_PERIOD = 12
TRIX_PERIOD = 15
TRIX_SIGNAL_PERIOD = 9
CMF_PERIOD = 21
CHOP_PERIOD = 14
CHOP_TRENDING_THRESHOLD = 38.2
CHOP_CHOPPY_THRESHOLD = 61.8
STOCH_RSI_PERIOD = 14
STOCH_RSI_SMOOTH = 3
STOCH_RSI_D_PERIOD = 3
MIN_ROWS_FOR_EMA200 = 200
CROSSOVER_LOOKBACK = 5
TREND_BASE_WEIGHT = 0.40
MOMENTUM_BASE_WEIGHT = 0.35
VOLATILITY_BASE_WEIGHT = 0.25
ADX_WEAK_THRESHOLD = 20
ADX_STRONG_THRESHOLD = 25
ADX_WEAK_TREND_MULTIPLIER = 0.5
ADX_STRONG_TREND_MULTIPLIER = 1.15
ADX_STRONG_BOLLINGER_DAMPEN = 0.5
BUY_THRESHOLD = 56
SELL_THRESHOLD = 44
EXCHANGE_SUFFIXES = {
    "NASDAQ": "",
    "NYSE": "",
    "NSE": ".NS",
    "BSE": ".BO",
    "LSE": ".L",
    "TSE": ".T",
    "HKEX": ".HK",
    "TSX": ".TO",
    "XETRA": ".DE",
    "ASX": ".AX",
    "SGX": ".SI",
    "EURONEXT": ".PA",
    "SIX": ".SW",
    "BME": ".MC",
    "OMX": ".ST",
    "JSE": ".JO",
    "BMF": ".SA",
    "KRX": ".KS",
    "TWSE": ".TW",
}
INDICES = {
    "S&P 500": "^GSPC",
    "Dow Jones": "^DJI",
    "Nasdaq": "^IXIC",
    "FTSE 100": "^FTSE",
    "Nikkei 225": "^N225",
    "DAX": "^GDAXI",
    "Nifty 50": "^NSEI",
    "Sensex": "^BSESN",
    "Hang Seng": "^HSI",
    "CAC 40": "^FCHI",
    "ASX 200": "^AXJO",
    "KOSPI": "^KS11",
    "Taiwan Weighted": "^TWII",
    "Shanghai Composite": "000001.SS",
}